using Pkg
#Pkg.add("Plots")
#Pkg.build("PyCall")
Pkg.add("Plots")
Pkg.add("PyPlot")
Pkg.add("FFTW")
#Pkg.add("Statistics")
#Pkg.add("WAV")
Pkg.add("DSP")
#Pkg.add("DelimitedFiles")
#Pkg.add("CSV")
#Pkg.add("Statistics")
Pkg.add("Interact")
Pkg.add("Mux")
#Pkg.add("Colors")
#Pkg.add("DataStructures")
#Pkg.add("InteractBulma")
